server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /api/cars {
        rewrite ^/api/cars(.*)$ /cars$1 break;
        proxy_pass http://myservice:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/customers {
        rewrite ^/api/customers(.*)$ /customers$1 break;
        proxy_pass http://customerservice:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
